<?php

/**
 * @file
 * Module for handling user oriented issues (login etc.)
 */


/**
 * Implementation of hook_init()
 */
function TPA_user_init() {
	global $user;
  if( $user->uid == 0 ) {
	  if ( !( arg(0) == 'user' && arg(1) == 'login' ) &&
	  		 !( arg(0) == 'feeds' ) ) {
	    if( !drupal_is_cli() ) {
	    	drupal_goto('user/login');
	    }
	  }
	}
}


/*
 * Implementation of hook_form_alter()
 */
function TPA_user_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
	  case 'user_login':
	  	$form['#submit'][] = 'TPA_user_login_form_submit';
	   
	    break;
	  }	
}


/**
 * Custom submit handler
 */
function TPA_user_login_form_submit($form, &$form_state){
  //Redirects to home page on login.
  $form_state['redirect'] = 'pois';
}
