<?php

/**
 * @file
 * Support module for Malmö Stad forum
 */

require_once( drupal_get_path('theme', 'touch_poi') . "/block/block-content-functions.inc" );

/**
 * Implementation of hook_block_info().
 */
function poi_content_block_info() {    
  $blocks['forum_footer_nav'] = array(
    'info' => t('Forum footer navigation'),
  );

  // Add poi
  $blocks['add_poi_link'] = array(
    'info' => t('Link to add new poi.'),
  );

  // Add subcategory
  $blocks['add_subcategory_link'] = array(
    'info' => t('Link to add new subcategory.'),
  );

  // Add category
  $blocks['add_category_link'] = array(
    'info' => t('Link to add new category.'),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function poi_content_block_view($delta = '') {
	$block = '';
  switch ($delta) {
    case 'forum_footer_nav':
    	$block['subject'] = '';
      $block['content'] = touch_poi_footer_nav();
      break;
    case 'add_poi_link':
      $block['subject'] = '';
      $block['pages'] = 'pois';
      $link_text = t('Add poi');
      $block['content'] = l( $link_text, 'node/add/poi');
      break;
    case 'add_subcategory_link':
      $block['subject'] = '';
      $block['pages'] = 'subcategories';
      $link_text = t('Add sub-category');
      $block['content'] = l( $link_text, 'node/add/subcategory');
      break;
    case 'add_category_link':
      $block['subject'] = '';
      $block['pages'] = 'categories';
      $link_text = t('Add category');
      $block['content'] = l( $link_text, 'node/add/category');
      break;
  }

  return $block;
}


/**
 * Implementation of hook_menu_alter().
 */
function poi_content_menu_alter(&$items) {
  
  // Page add/edit container only available to super admin 
  $items['admin/structure/forum/add/container']['access arguments'] = array('access administration pages');
  $items['admin/structure/forum/edit/container/%taxonomy_term'] = array('access administration pages'); 

  // Place add forum as tab menu
  $items['admin/structure/forum/add/forum']['type'] = MENU_LOCAL_TASK;

  // Remove settings from tab menu
  $items['admin/structure/forum/settings']['type'] = MENU_NORMAL_ITEM;
}


/**
 * Implementation of hook_theme().
 */
function poi_content_theme() {
    return array(
        'asset_button_link' => array(
            'render element' => 'element',
        ),
    );
}
