<?php

/**
 * @file
 * Module to handle pois, their content and categories
 */

require_once './' . drupal_get_path('module', 'TPA_poi_content') . '/feeds/subcategory.inc';
require_once './' . drupal_get_path('module', 'TPA_poi_content') . '/feeds/poi.inc';
require_once './' . drupal_get_path('module', 'TPA_poi_content') . '/includes/forms.inc';


/**
 * Implementation of hook_menu().
 */
function TPA_poi_content_menu() {
  $items['feeds/subcategories.xml'] = array(
      'page callback' => 'TPA_poi_content_subcategory_feed',
      'access arguments' => array('access content'),
  );

  $items['feeds/pois.xml'] = array(
      'page callback' => 'TPA_poi_content_poi_feed',
      'access arguments' => array('access content'),
  );

  return $items;
}    



/**
 * Implementation of hook_block_info().
 */
function TPA_poi_content_block_info() {    
  $blocks['TPA_forum_footer_nav'] = array(
    'info' => t('Forum footer navigation'),
  );

  // Add poi
  $blocks['TPA_add_poi_link'] = array(
    'info' => t('Link to add new poi.'),
  );

  // Add subcategory
  $blocks['TPA_add_subcategory_link'] = array(
    'info' => t('Link to add new subcategory.'),
  );

  // Add category
  $blocks['TPA_add_category_link'] = array(
    'info' => t('Link to add new category.'),
  );

  // Add category
  $blocks['TPA_iframe_map'] = array(
    'info' => t('Malmö stad map'),
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function TPA_poi_content_block_view($delta = '') {
	$block = '';
  switch ($delta) {
    case 'TPA_forum_footer_nav':
    	$block['subject'] = '';
      $block['content'] = touch_poi_footer_nav();
      break;
    case 'TPA_add_poi_link':
      $block['subject'] = '';
      $block['pages'] = 'pois';
      $link_text = t('Add poi');
      $block['content'] = l( $link_text, 'node/add/poi');
      break;
    case 'TPA_add_subcategory_link':
      $block['subject'] = '';
      $block['pages'] = 'subcategories';
      $link_text = t('Add sub-category');
      $block['content'] = l( $link_text, 'node/add/subcategory');
      break;
    case 'TPA_add_category_link':
      $block['subject'] = '';
      $block['pages'] = 'categories';
      $link_text = t('Add category');
      $block['content'] = l( $link_text, 'node/add/category');
      break;
    case 'TPA_iframe_map':
      $block['subject'] = '';
      //$block['content'] = "<iframe src='http://localhost/msmap/index.html?config=eurov.js' />";
      $block['content'] = "<iframe src='http://malmoevent.munkeby.se/map/leafsmap/?config=eurov.js&xy=13.0,55.6' />";
      
      break;
  }

  return $block;
}


/**
 * Implementation of hook_form_alter() for poi_node_form.
 */
function TPA_poi_content_form_poi_node_form_alter(&$form, &$form_state) {
  // Change max nr of chars for latitude and longitude fields
  $form['field_latitude']['und'][0]['value']['#maxlength'] = 100;
  $form['field_longitude']['und'][0]['value']['#maxlength'] = 100;

  // Add map handling
  drupal_add_js(  drupal_get_path('module', 'TPA_poi_content') . '/js/map.js', 
                  array(  'type' => 'file', 
                          'group' => JS_DEFAULT ) );
  
  // Display poi marker on map if coords exist
  $lat = $form['field_latitude']['und'][0]['value']['#entity']->field_latitude['und'][0]['value'];
  $lon = $form['field_longitude']['und'][0]['value']['#entity']->field_longitude['und'][0]['value'];

  if( $lat != '' && $lon != '' ) {
    $coord_parameter = '&xy=' . $lon . "," . $lat;
  } else {
    $coord_parameter = '';
  }

  // Add the map
  $form['malmostad_map'] = array(
    "#markup" => "<iframe  src='http://localhost/msmap/index.html?config=eurov.js" . $coord_parameter . "'
                                onload='Drupal.behaviors.mapInit.map_loaded()'
                                width=1200
                                height=600 
                                id='map_iframe' seamless>
                       </iframe>
                  ",
    "#weight" => 2,
  );

  

  // Disable / enable input fields based on chosen subcategory
  drupal_add_js(  drupal_get_path('module', 'TPA_poi_content') . '/js/disable_add_poi_fields.js', 
                  array(  'type' => 'file', 
                          'group' => JS_DEFAULT ) );
  
  // Remove preview button
  unset($form['actions']['preview']);

  // Submit
  $form['actions']['submit']['#submit'][] = 'TPA_add_poi_submit';
}

/**
 * Implementation of hook_form_alter() for subcategory_node_form.
 */
function TPA_poi_content_form_subcategory_node_form_alter(&$form, &$form_state) {
  // Preview
  unset($form['actions']['preview']);

  // Submit
  $form['actions']['submit']['#submit'][] = 'TPA_add_subcategory_submit';
}




/**
 * Implementation of hook_form_alter() for category_node_form.
 */
function TPA_poi_content_form_category_node_form_alter(&$form, &$form_state) {
  // Preview
  unset($form['actions']['preview']);

  // Submit
  $form['actions']['submit']['#submit'][] = 'TPA_add_category_submit';
}


