<?php

/**
 * @file
 * Helper module for anything theming
 */


/**
 * Implementation of hook_theme().
 */
function TPA_theming_theme() {
    return array(
        'asset_button_link' => array(
            'render element' => 'element',
        ),
    );
}

/**
 * Implementation of hook_custom_theme
 */
function TPA_theming_custom_theme() {
	if (arg(0) == 'subcategories' ) {
		//print "here";
		//die;
    return "TPA_malmo_assets";
  }
}