<?php

/**
 * @file
 * Helper module for anything theming
 */

require_once( drupal_get_path('module', 'TPA_theming') . "/includes/block-content.inc" );


/**
 * Implementation of hook_theme().
 */
function TPA_theming_theme() {
    return array(
        'TPA_asset_button_link' => array(
            'render element' => 'element',
        ),
        'category_node_form' => array( 
          'render element' => 'form', 
          'template' => 'category-node-form', 
          'path' => drupal_get_path('theme', 'TPA_malmo_assets/templates'),
        ),
        
    );
}

/**
 * Implementation of hook_custom_theme
 */
function TPA_theming_custom_theme() {
	if (	arg(0) == '' || 
				arg(0) == 'subcategories' || 
				arg(0) == 'categories' || 
				arg(0) == 'pois' || 
				(arg(0) == 'user' && arg(1) == 'login' ) || 
        (arg(0) == 'node' && arg(1) == 'add' && arg(2) == 'poi' ) ||
        (arg(0) == 'node' && arg(1) == 'add' && arg(2) == 'category' ) ) {
    return "TPA_malmo_assets";
  }
}


/**
 * Implementation of hook_block_info().
 */
function TPA_theming_block_info() {    
  $blocks['TPA_footer_nav'] = array(
    'info' => t('TPA footer navigation'),
  );

  return $blocks;
}


/**
 * Implementation of hook_block_view().
 */
function TPA_theming_block_view($delta = '') {
	$block = '';
  switch ($delta) {
    case 'TPA_footer_nav':
    	$block['subject'] = '';
      $block['content'] = TPA_theming_footer_nav();
      break;
  }

  return $block;
}
